name: Build master branch

on:
  push:
    branches:
      - master

jobs:
    ubuntu-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Ballerina build with tests
              uses: ballerina-platform/ballerina-action/@swan-lake-release
              with:
                args:
                  build -a
                  