name: Daily build

on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
    ubuntu-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Ballerina build with tests
              uses: ballerina-platform/ballerina-action/@swan-lake-release
              with:
                args:
                  build -a
                  