
name: Deployment

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Ballerina build with tests
              uses: ballerina-platform/ballerina-action/@swan-lake-release
              with:
                args:
                  build -a
